version: '2'
services:
  server:
    container_name: server
    build:
      context: ./
    image: server:latest
    ports:
      - "8080:8080"
    networks:
      - lab4-network
    depends_on:
      - db
      - redis
      - queue
  db:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: lab4_db
    ports:
      - "3307:3306"
    networks:
      - lab4-network
  redis:
    image: redis
    command: redis-server
    ports:
      - "6379:6379"
    networks:
      - lab4-network
  queue:
    image: rmohr/activemq
    container_name: queue
    ports:
      - "61616:61616"
    networks:
      - lab4-network
networks:
  lab4-network:
    driver: bridge